#!/usr/bin/env bash
# Sheenidoro — waybar integration for Omarchy.
#
# Installs the state helper, makes sure a `sheenidoro` launcher exists so the
# module's click actions actually do something, registers custom/sheenidoro in
# the bar, and restyles it. Safe to re-run.
set -euo pipefail

PROJECT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="$HOME/.config/waybar/config.jsonc"
STYLE="$HOME/.config/waybar/style.css"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/sheenidoro"
SHARE_DIR="$HOME/.local/share/sheenidoro"
BIN_DIR="$HOME/.local/bin"

echo "▮ Sheenidoro waybar setup"

# ── state dir ────────────────────────────────────────────────────────────────
mkdir -p "$STATE_DIR"
rm -f "$STATE_DIR/waybar.json"
echo "  state dir  $STATE_DIR (cleared — module stays hidden until the app runs)"

# ── helper script ────────────────────────────────────────────────────────────
mkdir -p "$SHARE_DIR"
if [ -f "$PROJECT/scripts/waybar-sheenidoro.sh" ]; then
  install -m755 "$PROJECT/scripts/waybar-sheenidoro.sh" "$SHARE_DIR/waybar-sheenidoro.sh"
elif [ -f /usr/share/sheenidoro/waybar-sheenidoro.sh ]; then
  install -m755 /usr/share/sheenidoro/waybar-sheenidoro.sh "$SHARE_DIR/waybar-sheenidoro.sh"
else
  echo "  ! helper script not found" >&2
  exit 1
fi
echo "  helper     $SHARE_DIR/waybar-sheenidoro.sh"

# ── launcher ─────────────────────────────────────────────────────────────────
# The module's on-click calls `sheenidoro`. When the pacman package is not
# installed that command does not exist and clicks silently do nothing, so
# fall back to a shim that runs the build in this checkout.
MARKER="# sheenidoro-generated-launcher"
FOUND="$(command -v sheenidoro 2>/dev/null || true)"
if [ -n "$FOUND" ] && ! grep -qF "$MARKER" "$FOUND" 2>/dev/null; then
  # a real install (pacman wrapper) wins — leave it alone
  LAUNCHER="$FOUND"
  echo "  launcher   $LAUNCHER (system)"
else
  # no install, or our own shim from a previous run: (re)write it
  mkdir -p "$BIN_DIR"
  LAUNCHER="$BIN_DIR/sheenidoro"
  cat > "$LAUNCHER" <<LAUNCH
#!/usr/bin/env bash
$MARKER
# Generated by sheenidoro setup-waybar.sh — runs the build in $PROJECT
APP="$PROJECT"
MAIN="\$APP/dist-electron/electron/main.js"
if [ ! -f "\$MAIN" ]; then
  echo "sheenidoro: \$MAIN missing — run 'npm run build:electron' in \$APP" >&2
  exit 1
fi
# node_modules/.bin/electron is a JS wrapper that exists even when the
# binary was never downloaded (npm ci --ignore-scripts), so point at the
# real executable and fall back to the system runtime.
for e in \\
  "\$APP/node_modules/electron/dist/electron" \\
  /usr/bin/electron37 \\
  "\$(command -v electron 2>/dev/null)"
do
  [ -n "\$e" ] && [ -x "\$e" ] && exec "\$e" --class=Sheenidoro "\$APP" "\$@"
done
echo "sheenidoro: no electron runtime found (install electron37)" >&2
exit 1
LAUNCH
  chmod +x "$LAUNCHER"
  echo "  launcher   $LAUNCHER (shim → $PROJECT)"
fi

# ── config.jsonc ─────────────────────────────────────────────────────────────
if [ -f "$CONFIG" ]; then
  cp "$CONFIG" "$CONFIG.bak.$(date +%s)"
  LAUNCHER="$LAUNCHER" HELPER="$SHARE_DIR/waybar-sheenidoro.sh" python3 - "$CONFIG" <<'PY'
import json, os, pathlib, re, sys

path = pathlib.Path(sys.argv[1])
text = path.read_text()
launcher, helper = os.environ["LAUNCHER"], os.environ["HELPER"]

# absolute paths for the click actions: waybar runs them through sh, which does
# not necessarily have ~/.local/bin on PATH
module = {
    "exec": helper,
    "return-type": "json",
    "interval": 1,
    "tooltip": True,
    "on-click": f"{launcher} --toggle",
    "on-click-right": f"{launcher} --show",
    "on-click-middle": f"{launcher} --skip",
}

def strip_jsonc(s):
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    return "\n".join(re.sub(r"\s*//.*$", "", ln) for ln in s.splitlines())

try:
    data = json.loads(strip_jsonc(text))
except Exception as e:
    print(f"  ! could not parse {path}: {e}")
    print("  ! add custom/sheenidoro by hand — see README")
    raise SystemExit(1)

changed = data.get("custom/sheenidoro") != module
data["custom/sheenidoro"] = module

placed = any(
    isinstance(data.get(k), list) and "custom/sheenidoro" in data[k]
    for k in ("modules-left", "modules-center", "modules-right")
)
if not placed:
    target = "modules-center" if "modules-center" in data else "modules-right"
    lst = data.get(target, [])
    lst.insert(lst.index("clock") + 1 if "clock" in lst else 0, "custom/sheenidoro")
    data[target] = lst
    changed = True
    print(f"  config     inserted custom/sheenidoro into {target}")

if changed:
    path.write_text(json.dumps(data, indent=2) + "\n")
    print(f"  config     {path} updated")
else:
    print(f"  config     {path} already current")
PY
else
  echo "  ! $CONFIG not found — skipping module registration"
fi

# ── style.css ────────────────────────────────────────────────────────────────
if [ -f "$STYLE" ]; then
  cp "$STYLE" "$STYLE.bak.$(date +%s)"
  python3 - "$STYLE" <<'PY'
import pathlib, re, sys

path = pathlib.Path(sys.argv[1])
text = path.read_text()

# drop any previous block: the delimited one, plus the legacy pastel rules
text = re.sub(r"/\* >>> sheenidoro >>> \*/.*?/\* <<< sheenidoro <<< \*/\n?", "", text, flags=re.S)
text = re.sub(r"/\*[^*]*[Ss]heenidoro[^*]*\*/\n?", "", text)
text = re.sub(r"#custom-sheenidoro[^{]*\{[^}]*\}\n?", "", text)
text = re.sub(r"\n{3,}", "\n\n", text).rstrip() + "\n"

text += """
/* >>> sheenidoro >>> */
#custom-sheenidoro {
  padding: 0 8px;
  margin: 0 6px;
  font-weight: bold;
  border-left: 2px solid #2c3238;
}
#custom-sheenidoro.focus {
  color: #ff0033;
  border-left-color: #ff0033;
}
#custom-sheenidoro.short {
  color: #00e5ff;
  border-left-color: #00e5ff;
}
#custom-sheenidoro.long {
  color: #ffb000;
  border-left-color: #ffb000;
}
#custom-sheenidoro.paused {
  color: #8b9199;
  border-left-color: #8b9199;
}
#custom-sheenidoro.idle {
  color: #6b7178;
  border-left-color: #2c3238;
}
/* not running: collapse the module entirely */
#custom-sheenidoro.hidden {
  opacity: 0;
  min-width: 0;
  margin: 0;
  padding: 0;
  border: none;
  font-size: 0;
}
/* <<< sheenidoro <<< */
"""
path.write_text(text)
print(f"  style      {path} updated")
PY
else
  echo "  ! $STYLE not found — skipping style"
fi

# ── reload ───────────────────────────────────────────────────────────────────
if command -v omarchy >/dev/null 2>&1; then
  omarchy restart waybar >/dev/null 2>&1 && echo "  waybar     restarted via omarchy"
elif pgrep -x waybar >/dev/null 2>&1; then
  pkill -SIGUSR2 waybar 2>/dev/null && echo "  waybar     reloaded (SIGUSR2)"
else
  echo "  waybar     not running"
fi

echo ""
echo "✔ done"
echo "  test helper : bash $SHARE_DIR/waybar-sheenidoro.sh"
echo "  launch app  : $LAUNCHER"
echo "  the module stays hidden until Sheenidoro is running."
